Default DB is in os.TempDir().  Also added .db file extension to database files
shreyb/fakeJobsub pull request #2
Opened 2024-12-12 17:32 UTC by shreyb

Implemented changes requested by @retzkek in #1.

2024-12-16 16:58 UTC, shreyb commented
@retzkek - I think I can't request you to review this since you're not a "collaborator" on this repo.  Whenever you have time, could you take a quick look and let me know what you think?

2024-12-16 17:51 UTC, retzkek requested changes
Not that this is going to run anywhere with non-forward-slash path separators, but you should use `filepath.Join()` instead of `path.Join()'. https://pkg.go.dev/path/filepath@go1.23.4#Join

(sorry I was slow to accept the invite)

2024-12-16 19:11 UTC, shreyb commented
Good call.  Changed. 

(and no worries - at this point, this is just a reference for new FNAL gophers)

2025-01-07 22:54 UTC, retzkek approved these changes
LGTM

2025-01-07 23:04 UTC, merged